title: Joe S
url: "https://joesynth.github.io"
baseurl: ""
permalink: /:title.html

# Essencial para funcionar SEM Front Matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
